---
title: "其他交通工具的影響"
output: html_notebook
---

```{r}
library(readxl)
bus <-  read_excel("data/bus_efficiency_revised.xlsx", sheet = 2)
```

```{r}
years <- unique(bus$Year)
column <- colnames(bus)
bus_avg <- vector(mode="numeric", length = length(column))
for(i in 1:length(years)) {
  row <- vector(mode="numeric", length = length(column))
  row[1] <- years[i]
  row[2] <- sum(bus$Year == years[i])
  tmp <- bus[bus$Year == years[i],]
  for(j in 3:length(column)) {
    row[j] <- mean(as.numeric(unlist(bus[bus$Year == years[i],column[j]])))
  }
  bus_avg <- rbind(bus_avg, row)
}

bus_avg <- data.frame(bus_avg[2:nrow(bus_avg),], row.names = NULL, stringsAsFactors=FALSE)
colnames(bus_avg) <- c("Year", "Counts", column[3:length(column)])
bus_avg <- data.frame(lapply(bus_avg,as.numeric))
print(bus_avg)
```

read data: MRT/ubike/機動車輛(計程車、機車、自用客車與貨車)
```{r}
MRT <- read_excel("data/statistic_project_data.xlsx", sheet = "MRT")
ubike <- read_excel("data/statistic_project_data.xlsx", sheet = "Ubike")
vehicle <- read_excel("data/statistic_project_data.xlsx", sheet = "motor vehicle(Taipei)")
#taxi <- vechicle$Taxi
#motorcycle <- vechicle$Motorcycle
#private <- vechicle$`Private vehicle`
```

#### MRT

Scatter Diagram
```{r}
xlab <- c("MRT-Station","MRT-Times","MRT-Passenger","MRT-Discount")
ylab <- c("Bus Times", "Bus Length", "Bus Customer", "Bus Average.Customer", "Bus Profit", "Bus Average.Profit")
xunit <- c("(stations)","(times)","(people)","(1000 people)")
yunit <- c("(10000 times)", "(10000 km)","(10000 people)", "(people)","(10000 dollars)", "(dollars)")

for(i in 2:5){
  for(j in 3:8){
    x <- as.numeric(unlist(MRT[,i]))
    y <- bus_avg[,j]
       
    plot(x, y,xlab = paste(xlab[i-1],xunit[i-1]), ylab = paste(ylab[j-2],yunit[j-2]), main = paste("Year 86~107", xlab[i-1], " - ", ylab[j-2], "Scatter Diagram"))
    abline(lm(y~x))
  }
}
```

Coefficient of correlation
```{r}
cor(bus_avg[,3:ncol(bus_avg)], MRT[,2:5])
#MRT : Station 站數 / MRT	車次 / Passenger人次 / Discount_1K 雙向轉乘優惠運量 (千人次)
```
#### Ubike

Scatter Diagram
```{r}
ylab <- c("Bus Times", "Bus Length", "Bus Customer", "Bus Average.Customer", "Bus Profit", "Bus Average.Profit")
yunit <- c("(10000 times)", "(10000 km)","(10000 people)", "(people)","(10000 dollars)", "(dollars)")
for(i in 3:8){
  x <- bus_avg[(nrow(bus_avg)-9):nrow(bus_avg),i]
  y <- as.numeric(unlist(ubike[,2]))
  plot(x, y, xlab = "Ubike rental(times)",ylab = paste(ylab[i-2],yunit[i-2]), main = paste("Year 98~107 Ubike - ", ylab[i-2], "Scatter Diagram"))
  abline(lm(y ~ x))
}
```
Coefficient of correlation
```{r}
tmp <- bus_avg[(nrow(bus_avg)-9):nrow(bus_avg) ,3:ncol(bus_avg)] #year: 98-107
#print(tmp)
cor(tmp[,], ubike[,2])
```

#### Motor vehicle

Scatter Diagram
```{r}
xlab <- c("Taxi","Motorcycle","Private Vehicle")
ylab <- c("Bus Times", "Bus Length", "Bus Customer", "Bus Average.Customer", "Bus Profit", "Bus Average.Profit")
yunit <- c("(10000 times)", "(10000 km)","(10000 people)", "(people)","(10000 dollars)", "(dollars)")

for(i in 2:4){
  for(j in 3:8){
    x <- as.numeric(unlist(vehicle[,i]))
    y <- bus_avg[,j]
       
    plot(x, y,xlab = xlab[i-1], ylab = paste(ylab[j-2], yunit[j-2]), main = paste("Year 86~107", xlab[i-1], " - ", ylab[j-2], "Scatter Diagram"))
    abline(lm(y ~ x))
  }
}

```

Coefficient of correlation
```{r}
veh_cor <- cor(bus_avg[,3:ncol(bus_avg)], vehicle[2:4])
print(veh_cor)
```




```{r}
for(co in colnames(MRT)[2:ncol(MRT)]) {
  plot(MRT[, c("Year", co)], main=gsub("\\.", " ", paste("Line Chart of ", co), ".", " "))
  lines(MRT[, c("Year", co)])
}
```
```{r}
plot(ubike, main="Line Chart of Ubike")
lines(ubike$Year, ubike$Ubike)
```

```{r}
for(co in colnames(vehicle)[2:ncol(vehicle)]) {
  plot(vehicle[, c("Year", co)], main=gsub("\\.", " ", paste("Line Chart of ", co), ".", " "))
  lines(vehicle[, c("Year", co)])
}
```

